---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-template-go
spec:
  # package: xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1
  xrender.crossplane.io/runtime: Development
  xrender.crossplane.io/runtime-development-target: localhost:9443
